/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  chatSessionContinue,
  ContinueAcceptEnum,
} from "../funcs/chatSessionContinue.js";
import {
  chatSessionCreate,
  CreateAcceptEnum,
} from "../funcs/chatSessionCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { CreateAcceptEnum } from "../funcs/chatSessionCreate.js";

export { ContinueAcceptEnum } from "../funcs/chatSessionContinue.js";

export class ChatSession extends ClientSDK {
  /**
   * Create Chat Session
   */
  async create(
    request: components.CreateChatSessionWithChatResultInput,
    options?: RequestOptions & { acceptHeaderOverride?: CreateAcceptEnum },
  ): Promise<operations.CreateResponse> {
    return unwrapAsync(chatSessionCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Continue Chat Session
   */
  async continue(
    chatSessionId: string,
    continueChatSessionWithChatResultInput:
      components.ContinueChatSessionWithChatResultInput,
    options?: RequestOptions & { acceptHeaderOverride?: ContinueAcceptEnum },
  ): Promise<operations.ContinueResponse> {
    return unwrapAsync(chatSessionContinue(
      this,
      chatSessionId,
      continueChatSessionWithChatResultInput,
      options,
    ));
  }
}
