/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { ChatSession } from "./chatsession.js";

export class InkeepAI extends ClientSDK {
  private _chatSession?: ChatSession;
  get chatSession(): ChatSession {
    return (this._chatSession ??= new ChatSession(this._options));
  }
}
