/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { EventStream } from "../../lib/event-streams";
import * as components from "../../models/components";
import { z } from "zod";

export type ContinueChatSessionWithChatResultRequest = {
    chatSessionId: string;
    continueChatSessionWithChatResultInput: components.ContinueChatSessionWithChatResultInput;
};

export type ContinueChatSessionWithChatResultResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successful Response
     */
    chatResult?: components.ChatResult | undefined;
    /**
     * Successful Response
     */
    chatResultStreamEvent?: EventStream<components.ChatResultStreamEvent> | undefined;
};

/** @internal */
export namespace ContinueChatSessionWithChatResultRequest$ {
    export type Inbound = {
        chat_session_id: string;
        ContinueChatSessionWithChatResultInput: components.ContinueChatSessionWithChatResultInput$.Inbound;
    };

    export const inboundSchema: z.ZodType<
        ContinueChatSessionWithChatResultRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            chat_session_id: z.string(),
            ContinueChatSessionWithChatResultInput:
                components.ContinueChatSessionWithChatResultInput$.inboundSchema,
        })
        .transform((v) => {
            return {
                chatSessionId: v.chat_session_id,
                continueChatSessionWithChatResultInput: v.ContinueChatSessionWithChatResultInput,
            };
        });

    export type Outbound = {
        chat_session_id: string;
        ContinueChatSessionWithChatResultInput: components.ContinueChatSessionWithChatResultInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ContinueChatSessionWithChatResultRequest
    > = z
        .object({
            chatSessionId: z.string(),
            continueChatSessionWithChatResultInput:
                components.ContinueChatSessionWithChatResultInput$.outboundSchema,
        })
        .transform((v) => {
            return {
                chat_session_id: v.chatSessionId,
                ContinueChatSessionWithChatResultInput: v.continueChatSessionWithChatResultInput,
            };
        });
}

/** @internal */
export namespace ContinueChatSessionWithChatResultResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        ChatResult?: components.ChatResult$.Inbound | undefined;
        ChatResultStreamEvent?: ReadableStream<Uint8Array> | undefined;
    };

    export const inboundSchema: z.ZodType<
        ContinueChatSessionWithChatResultResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            ChatResult: components.ChatResult$.inboundSchema.optional(),
            ChatResultStreamEvent: z
                .instanceof(ReadableStream<Uint8Array>)
                .transform((stream) => {
                    return new EventStream({
                        stream,
                        decoder(rawEvent) {
                            const schema = components.ChatResultStreamEvent$.inboundSchema;
                            return schema.parse(rawEvent);
                        },
                    });
                })
                .optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.ChatResult === undefined ? null : { chatResult: v.ChatResult }),
                ...(v.ChatResultStreamEvent === undefined
                    ? null
                    : { chatResultStreamEvent: v.ChatResultStreamEvent }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        ChatResult?: components.ChatResult$.Outbound | undefined;
        ChatResultStreamEvent?: never | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ContinueChatSessionWithChatResultResponse
    > = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            chatResult: components.ChatResult$.outboundSchema.optional(),
            chatResultStreamEvent: z.never().optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.chatResult === undefined ? null : { ChatResult: v.chatResult }),
                ...(v.chatResultStreamEvent === undefined
                    ? null
                    : { ChatResultStreamEvent: v.chatResultStreamEvent }),
            };
        });
}
