/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { RecordsCited, RecordsCited$ } from "./recordscited";
import { z } from "zod";

export type AssistantMessageResponse = {
    content: string;
    recordsCited?: RecordsCited | undefined;
};

/** @internal */
export namespace AssistantMessageResponse$ {
    export type Inbound = {
        content: string;
        records_cited?: RecordsCited$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<AssistantMessageResponse, z.ZodTypeDef, Inbound> = z
        .object({
            content: z.string(),
            records_cited: RecordsCited$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                content: v.content,
                ...(v.records_cited === undefined ? null : { recordsCited: v.records_cited }),
            };
        });

    export type Outbound = {
        content: string;
        records_cited?: RecordsCited$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AssistantMessageResponse> = z
        .object({
            content: z.string(),
            recordsCited: RecordsCited$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                content: v.content,
                ...(v.recordsCited === undefined ? null : { records_cited: v.recordsCited }),
            };
        });
}
