/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { MessageChunk, MessageChunk$ } from "./messagechunk";
import { z } from "zod";

export enum Event {
    MessageChunk = "message_chunk",
}

/**
 * A server-sent event containing a chunk of the message.
 */
export type ChatResultMessageChunkEvent = {
    event: Event;
    data: MessageChunk;
};

/** @internal */
export const Event$ = z.nativeEnum(Event);

/** @internal */
export namespace ChatResultMessageChunkEvent$ {
    export type Inbound = {
        event: Event;
        data: string;
    };

    export const inboundSchema: z.ZodType<ChatResultMessageChunkEvent, z.ZodTypeDef, Inbound> = z
        .object({
            event: Event$,
            data: z
                .string()
                .transform((v, ctx) => {
                    try {
                        return JSON.parse(v);
                    } catch (err) {
                        ctx.addIssue({
                            code: z.ZodIssueCode.custom,
                            message: `malformed json: ${err}`,
                        });
                        return z.NEVER;
                    }
                })
                .pipe(MessageChunk$.inboundSchema),
        })
        .transform((v) => {
            return {
                event: v.event,
                data: v.data,
            };
        });

    export type Outbound = {
        event: Event;
        data: MessageChunk$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ChatResultMessageChunkEvent> = z
        .object({
            event: Event$,
            data: MessageChunk$.outboundSchema,
        })
        .transform((v) => {
            return {
                event: v.event,
                data: v.data,
            };
        });
}
