/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { RecordsCited, RecordsCited$ } from "./recordscited";
import * as z from "zod";

export enum ChatResultRecordsCitedEventEvent {
    RecordsCited = "records_cited",
}

/**
 * A server-sent event with information about the records cited in the message.
 */
export type ChatResultRecordsCitedEvent = {
    event: ChatResultRecordsCitedEventEvent;
    data: RecordsCited;
};

/** @internal */
export const ChatResultRecordsCitedEventEvent$ = z.nativeEnum(ChatResultRecordsCitedEventEvent);

/** @internal */
export namespace ChatResultRecordsCitedEvent$ {
    export type Inbound = {
        event: ChatResultRecordsCitedEventEvent;
        data: string;
    };

    export const inboundSchema: z.ZodType<ChatResultRecordsCitedEvent, z.ZodTypeDef, Inbound> = z
        .object({
            event: ChatResultRecordsCitedEventEvent$,
            data: z
                .string()
                .transform((v, ctx) => {
                    try {
                        return JSON.parse(v);
                    } catch (err) {
                        ctx.addIssue({
                            code: z.ZodIssueCode.custom,
                            message: `malformed json: ${err}`,
                        });
                        return z.NEVER;
                    }
                })
                .pipe(RecordsCited$.inboundSchema),
        })
        .transform((v) => {
            return {
                event: v.event,
                data: v.data,
            };
        });

    export type Outbound = {
        event: ChatResultRecordsCitedEventEvent;
        data: RecordsCited$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ChatResultRecordsCitedEvent> = z
        .object({
            event: ChatResultRecordsCitedEventEvent$,
            data: RecordsCited$.outboundSchema,
        })
        .transform((v) => {
            return {
                event: v.event,
                data: v.data,
            };
        });
}
