/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ChatSessionInput, ChatSessionInput$ } from "./chatsessioninput";
import { z } from "zod";

export enum Two {
    Auto = "auto",
}

export enum One {
    Turbo = "turbo",
}

export type ChatMode = One | Two;

export type CreateChatSessionWithChatResultInput = {
    integrationId: string;
    chatSession: ChatSessionInput;
    chatMode?: One | Two | undefined;
    stream?: boolean | undefined;
};

/** @internal */
export const Two$ = z.nativeEnum(Two);

/** @internal */
export const One$ = z.nativeEnum(One);

/** @internal */
export namespace ChatMode$ {
    export type Inbound = One | Two;

    export type Outbound = One | Two;

    export const inboundSchema: z.ZodType<ChatMode, z.ZodTypeDef, Inbound> = z.union([One$, Two$]);

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ChatMode> = z.union([
        One$,
        Two$,
    ]);
}

/** @internal */
export namespace CreateChatSessionWithChatResultInput$ {
    export type Inbound = {
        integration_id: string;
        chat_session: ChatSessionInput$.Inbound;
        chat_mode?: One | Two | undefined;
        stream?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<
        CreateChatSessionWithChatResultInput,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            integration_id: z.string(),
            chat_session: ChatSessionInput$.inboundSchema,
            chat_mode: z.union([One$, Two$]).optional(),
            stream: z.boolean().default(false),
        })
        .transform((v) => {
            return {
                integrationId: v.integration_id,
                chatSession: v.chat_session,
                ...(v.chat_mode === undefined ? null : { chatMode: v.chat_mode }),
                ...(v.stream === undefined ? null : { stream: v.stream }),
            };
        });

    export type Outbound = {
        integration_id: string;
        chat_session: ChatSessionInput$.Outbound;
        chat_mode?: One | Two | undefined;
        stream: boolean;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateChatSessionWithChatResultInput
    > = z
        .object({
            integrationId: z.string(),
            chatSession: ChatSessionInput$.outboundSchema,
            chatMode: z.union([One$, Two$]).optional(),
            stream: z.boolean().default(false),
        })
        .transform((v) => {
            return {
                integration_id: v.integrationId,
                chat_session: v.chatSession,
                ...(v.chatMode === undefined ? null : { chat_mode: v.chatMode }),
                stream: v.stream,
            };
        });
}
