/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum RecordTypeEnumerated {
    Documentation = "documentation",
    Site = "site",
    DiscoursePost = "discourse_post",
    GithubIssue = "github_issue",
    GithubDiscussion = "github_discussion",
    StackoverflowQuestion = "stackoverflow_question",
    DiscordForumPost = "discord_forum_post",
    DiscordMessage = "discord_message",
    CustomQuestionAnswer = "custom_question_answer",
}

/**
 * The type of record
 */
export type RecordType = RecordTypeEnumerated | string;

/** @internal */
export const RecordTypeEnumerated$: z.ZodNativeEnum<typeof RecordTypeEnumerated> =
    z.nativeEnum(RecordTypeEnumerated);

/** @internal */
export namespace RecordType$ {
    export type Inbound = RecordTypeEnumerated | string;

    export type Outbound = RecordTypeEnumerated | string;
    export const inboundSchema: z.ZodType<RecordType, z.ZodTypeDef, Inbound> = z.union([
        RecordTypeEnumerated$,
        z.string(),
    ]);
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RecordType> = z.union([
        RecordTypeEnumerated$,
        z.string(),
    ]);
}
