/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = {
    apiKey: string;
};

/** @internal */
export namespace Security$ {
    export type Inbound = {
        api_key: string;
    };

    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, Inbound> = z
        .object({
            api_key: z.string(),
        })
        .transform((v) => {
            return {
                apiKey: v.api_key,
            };
        });

    export type Outbound = {
        api_key: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            apiKey: z.string(),
        })
        .transform((v) => {
            return {
                api_key: v.apiKey,
            };
        });
}
