/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum Role {
    User = "user",
}

export type UserMessage = {
    role: Role;
    content: string;
};

/** @internal */
export const Role$ = z.nativeEnum(Role);

/** @internal */
export namespace UserMessage$ {
    export type Inbound = {
        role: Role;
        content: string;
    };

    export const inboundSchema: z.ZodType<UserMessage, z.ZodTypeDef, Inbound> = z
        .object({
            role: Role$,
            content: z.string(),
        })
        .transform((v) => {
            return {
                role: v.role,
                content: v.content,
            };
        });

    export type Outbound = {
        role: Role;
        content: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UserMessage> = z
        .object({
            role: Role$,
            content: z.string(),
        })
        .transform((v) => {
            return {
                role: v.role,
                content: v.content,
            };
        });
}
