/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UserMessage = {
    role?: "user" | undefined;
    content: string;
};

/** @internal */
export namespace UserMessage$ {
    export const inboundSchema: z.ZodType<UserMessage, z.ZodTypeDef, unknown> = z.object({
        role: z.literal("user").optional(),
        content: z.string(),
    });

    export type Outbound = {
        role: "user";
        content: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UserMessage> = z.object({
        role: z.literal("user").default("user" as const),
        content: z.string(),
    });
}
